from typing import Protocol

from entity.loan import Loan


class LoanRepositoryPort(Protocol):
    async def get_by_id(self, loan_id: str) -> Loan | None: ...
    async def create(self, user_id: str, amount: float) -> Loan: ...
    async def update_status_if(self, loan_id: str, from_status: str, to_status: str) -> Loan | None: ...
    async def update_status(self, loan_id: str, status: str) -> None: ...
    async def save_evaluation(self, loan_id: str, score: int, status: str) -> Loan | None: ...
    async def apply_payment(
        self, loan_id: str, amount: float, new_status: str,
    ) -> Loan | None: ...
