from typing import Protocol


class OutboxRepositoryPort(Protocol):
    async def save(self, destination: str, payload: dict) -> dict: ...
    async def get_pending(self, limit: int = 10) -> list[dict]: ...
    async def mark_sent(self, outbox_id: int) -> None: ...
    async def increment_retry(self, outbox_id: int) -> None: ...
    async def mark_dead_letter(self, outbox_id: int) -> None: ...
