from typing import Protocol

from entity.user import User


class UserRepositoryPort(Protocol):
    async def get_by_id(self, user_id: str) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def create(self, email: str, name: str) -> User: ...
